### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d

### ISSUE THREAD

**Issue by Patrikkk** [fabrree/videoGenerator#2]
```
Checking data....
scrapeVideos()
Trying to request Pexels page with your api key
Everything went well! Starting to create videos now!
scrapeVideos()
Trying to request Pexels page with your api key
Going to scrape video with id:  4937376
100%|██████████████████████████████████████████| 34.7M/34.7M [00:03<00:00, 9.59MiB/s]
Traceback (most recent call last):
  File "C:\Users\patri\Downloads\videoGenerator-master\videoGenerator-master\main.py", line 320, in <module>
    videoloop = mainVideoLoop(data)
  File "C:\Users\patri\Downloads\videoGenerator-master\videoGenerator-master\main.py", line 236, in mainVideoLoop
    quoteText = getQuote()
  File "C:\Users\patri\Downloads\videoGenerator-master\videoGenerator-master\main.py", line 89, in getQuote
    lines = file.readlines()
  File "C:\Users\patri\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 3829: character maps to <undefined>
```

Getting this error. both on latest commit and release. 
(Got a different error before that. Which was about not finding path to tempFiles. Created the folder manually solved that issue, but this remains. 
I did install all requirements. 
Running Python 3.10.

**Comment by DuxSec** [comment]
Fixed with latest release
